### ISSUE TITLE
Item models for slabs don't put _slab at the end, causing them to generate models of full blocks (may apply to stairs and walls)

### ISSUE THREAD

**Issue by Cart3r1234** [Deviouslrd/json-generator#10]

**Comment by Deviouslrd** [comment]
Already resolved in #8 smh, so fixed in alpha 1.2, unless this is also for 1.2

**Comment by Deviouslrd** [comment]
Correction: this is for item models, and also applies to 1.2, and i know the issue already, will be fixed in 1.3 when i get around to it again
