### ISSUE TITLE
[SUGGESTION] Allow ability to get "stonecutting" and "from_stonecutting" recipies.

### ISSUE THREAD

**Issue by Jiingy** [Deviouslrd/json-generator#37]
As an example, I can use the generator to make a stonecutter recipe for my cut red sandstone wall and stair using either cut red sandstone or red sandstone, but not both at the same time.
![image](https://user-images.githubusercontent.com/69827559/107335788-377f4800-6a6d-11eb-80ef-77ced6749721.png)
![image](https://user-images.githubusercontent.com/69827559/107335801-3bab6580-6a6d-11eb-9b81-8035c8c6cbdc.png)

In this given example, I can only use the generator to either have cut red sandstone give me the recipe, or red sandstone, but not both. (This functionality is vanilla to default sandstone with you being able to use sandstone and cut sandstone to get a cut sandstone slab)

**Comment by Jiingy** [comment]
After doing a bit of digging it turns out my suggestion was a bit off, apparently how mojang does it is that they just have it set up like this:

"[output block]\_from_[input block]_stonecutting.json"

Would it be possible to make it so that you can choose the input and output block and therefore add different recipes for the same block?

![image](https://user-images.githubusercontent.com/69827559/107337051-b4f78800-6a6e-11eb-9f64-0fceb2b1ad5c.png)

**Comment by Deviouslrd** [comment]
Yeah a simple radio button selection could work, wouldn't be hard at all

**Comment by Deviouslrd** [comment]
Got this working
