### ISSUE TITLE
[BUG] Item models for Brick slabs and stairs don't properly chop the "s" in bricks, leading to them parenting to "bricks_slabs" and "bricks_stairs"

### ISSUE THREAD

**Issue by Cart3r1234** [Deviouslrd/json-generator#49]
Item models for brick stairs and slabs don't properly parent to the respective blocks due to the s in bricks not being dropped.  Walls work fine for some reason despite slabs and stairs not working.

![image](https://user-images.githubusercontent.com/69820300/122660918-47addf00-d153-11eb-8e93-25a3b5c29d01.png)

**Comment by Siuolplex** [comment]
Ill try to fix this in a PR

**Comment by Deviouslrd** [comment]
I'm not all that sure where the error would be coming from. I have it made so that any occurence of 'bricks' would be replaced by 'brick'. Cannot test it right now though.

**Comment by Deviouslrd** [comment]
Fixed in https://github.com/Deviouslrd/json-generator/commit/06e19644ae6e3e76db7b948a84d3b6cc82dd1691
Or maybe before that, im not entirely sure. Either way its fixed
