### ISSUE TITLE
[Suggestion] Allow different save locations for Recipes/advancements/loot tables than models/blockstates

### ISSUE THREAD

**Issue by Cart3r1234** [Deviouslrd/json-generator#6]

**Comment by Deviouslrd** [comment]
When the generator repalces the value in the save location box, it pulls from the app's localstorage to remember what the inputs on the previous page were.
Making this work would involve creating another localstorage entry, and loading that specific one on the page, and all that jazz. Switching between the block models or whatever and then going onto recipes and stuff would be the more difficult thing than switching between same save location bits and stuff, however im sue i could figure it out.

Will definitely consider implementing this.
